FROM      resin/%%RESIN_MACHINE_NAME%%-node:5.7

RUN       wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.50.tar.gz && \
          tar zxvf bcm2835-1.50.tar.gz && \
          cd bcm2835-1.50 && \
          ./configure && \
          make CFLAGS='-g -O2 -fPIC' && \
          make install && \
          mkdir -p /app

CMD       node main.js

WORKDIR   /app

COPY      package.json ./.
RUN       npm install

COPY      main.js ./.

